server: # HTTP 服务器
  port: ${SERVER_PORT} # 监听的端口
  mode: ${SERVER_MODE}

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}
  charset: ${DB_CHARSET}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: ${REDIS_DB}

jwt: # 通过 openssl rand -base64 32 生成
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}

rate_limit:
  requests_per_minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE}